### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by cjmateoo0221** [wiwidnadw/ESP32-Android-Studio#1]
Sir can you help me i cant seem to make it work

**Comment by cjmateoo0221** [comment]
![image](https://user-images.githubusercontent.com/92494422/146931209-238bcb8b-6748-4d91-827c-98e08ab58351.png)

**Comment by wiwidnadw** [comment]
Dont u mention okhttp on ur build.gradle sir? If u dont, try to insert that

**Comment by cjmateoo0221** [comment]
Already done sir, 
![image](https://user-images.githubusercontent.com/92494422/147042162-731598b5-fcc9-45bf-8d7c-51105685a70c.png)

**Comment by cjmateoo0221** [comment]
Also i have an error in this.

**Comment by cjmateoo0221** [comment]
![image](https://user-images.githubusercontent.com/92494422/147042750-b7580d18-7a5b-4f72-8c29-bdf882014d98.png)

**Comment by cjmateoo0221** [comment]
Sir upon troubleshooting. The issue was coming from the ESP32. It isn't able to make a wifi server. What should i do sir? I followed your arduino code.

Im using an ESP32- ESP32WROOM32

**Comment by wiwidnadw** [comment]
Do u ever try to access ur ESP32 from web ? What is message coming from
serial monitor ?
If doesnt response, u can try my code for visual studio project but the
code for "client.print" use from existing
