### ISSUE TITLE
How to LED off when Esp disconnected from Hotspot ?

### ISSUE THREAD

**Issue by BayuFadza** [wiwidnadw/ESP32-Android-Studio#2]
Hello, my name is Bayu. I have a problem with my project. 
-In Mode A-A = Led 2 and 3 ON. I want Led 2 and 3 Off when I disconnecting hotspot.
-but, I want too not occured when we chose mode A and hotspot disconnected, Led2 and Led3 still ON.
I not yet get the solution. Do you can help me ?

This is my Sketch. I hope you can help me. Thanks you !

      #include <WiFi.h>

    #define led1    2
    #define led2    4
    #define led3    12
    #define led4    14
    

    const char* ssid     = "xxxxxx";
    const char* password = "xxxxxx";

    unsigned long previousMillis = 0;
    unsigned long interval = 5000;

    WiFiServer server(80);

    void setup(){
    Serial.begin(115200);
    pinMode(led1,OUTPUT);
    pinMode(led2,OUTPUT);
    pinMode(led3,OUTPUT);
    pinMode(led4,OUTPUT);
    delay(10);
 
    // First connecting 
    Serial.println();
    Serial.println();
    Serial.print("Connecting to ");
    Serial.println(ssid);

    //WiFi.config
    WiFi.mode(WIFI_STA); //
    WiFi.begin(ssid, password);

    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }

    Serial.println("");
    Serial.println("WiFi connected.");
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());
    server.begin();

     void loop(){
     unsigned long currentMillis = millis();
     // if WiFi is down, try reconnecting every CHECK_WIFI_TIME seconds
     if ((WiFi.status() != WL_CONNECTED) && (currentMillis - previousMillis >=interval)) {
     Serial.begin(115200);
     Serial.print(millis());
     Serial.println("Reconnecting to WiFi...");

     // Wifi Disconnected
     while (WiFi.status() != WL_DISCONNECTED) {
        delay(500);
     }
     WiFi.disconnect();
     Serial.println("");
     Serial.println("Wifi disconnected.");
     server.begin();
     WiFi.begin(ssid, password);
     previousMillis = currentMillis;

    // Wifi Try Connecting
    while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
    }
    Serial.println("");
    Serial.println("WiFi connected.");
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());
    server.begin();
    previousMillis = currentMillis;
    String c = "WiFi connected.";
    
      WiFiClient client = server.available();
      if (!client) {
      return;
      }
      Serial.println("New Client."); 
      while(!client.available()) {
      delay(1);
      }

      String request = client.readStringUntil('\r');
      Serial.print(request);

  

      //  Mode Normal
      if (request.indexOf("A") != -1 ){
      digitalWrite(led1, LOW);
      }

      // Mode A
      if (request.indexOf("A") != -1 ) {
      digitalWrite(led2,HIGH);
      digitalWrite(led3,HIGH);             
      }

      // Mode B
      if (request.indexOf("B") != -1 ){
      digitalWrite(led2,LOW);
      digitalWrite(led3,LOW);   
      }
   
      // Mode Safe
      if (request.indexOf("A-A") != -1 ){
       digitalWrite(led1,HIGH);   
       digitalWrite(led3,LOW); 
      }

      // Mode A-A
      if (request.indexOf("A-A") != -1 )
       {
       digitalWrite(led2,HIGH);
       digitalWrite(led3,HIGH);
       }
       
       // Mode B-B
       if (request.indexOf("B-B") != -1 ){
       digitalWrite(led2,LOW);
       digitalWrite(led3,LOW);   
       }
    

    
      client.println("HTTP/1.1 200 OK");
      client.println("Content-type:text/html");
      client.println("");
  
      client.print(",");
      //client.print(sensorvalue);
      delay(1);
      }

**Comment by wiwidnadw** [comment]
Hello Bayu, hope u feel good today
I didnt see if mode A-A make ur both led turn on sir, it just make one of
them on. Next for ur wish to make all of ur led turn off when mode A-A and
connection lost maybe u need insert "while" with logic "wifi.status" inside
code "if request index of mode A-A"

Hope it answer ur question, thanks

**Comment by BayuFadza** [comment]
Sorry that sketch have a bit incorrect word.
From your correction (Insert the "while" & "wifi.status"), Is this my sketch right ?

       // Mode A-A
       if (request.indexOf("A-A") != -1 )
       {
       while (WiFi.status() != WL_DISCONNECTED) { 
        digitalWrite(R2,LOW);
        digitalWrite(R3,LOW);  
       }
       digitalWrite(R2,HIGH);
       digitalWrite(R3,HIGH);
       }

I trying that sketch and its work, A-A mode (R2 and R3 off when disconnected).
But, the Loading (in google) get stuck. I can't switch other mode again. All mode can't turn on caused the stuck loading (google).

In serial monitor, if request is sucessfully sending (no stuck loading)  :

       New Client.
       GET /IGonSafe HTTP/1.1
       GET /Favicon.ico HTTP/1.1

But if the Loading get stuck, All mode and led not work again :

       New Client.
       GET /IGonSafe HTTP/1.1New Client

(No  GET /Favicon.ico HTTP/1.1)

**Comment by wiwidnadw** [comment]
Yeah its appear because ur connection from google (client) to esp32 (server) was dicsonnected. So ur Google was loading because google (client) cant reach esp32 (server)
maybe u need to reconnect ur ESP32 into hotspot again
u can make sure thats issue happen on your sketch because disconnected moment by using serial monitor "serial println(wifi.status)" when disconnected happen.

**Comment by BayuFadza** [comment]
That happen when my server connected again. The Stuck loading when switching to mode A-A, B-B, and All mode. Its occured since I take that "while" and "wifi.status" in "if request.. (mode A-A)"
Is my "while" sketch is wrong ? :D

 if I deleted that "while" and logic "Wifi.status".... the sketch is Normal again. But, we can't get disconnect function to turn off led. hehe

**Comment by BayuFadza** [comment]
That happen when server is connected .
In First the Mode A-A have Stuck loading although A-A is already turn on the LED but its Can't switching to other mode again cause stuck loading ... Its different when other mode selected first, the loading other mode is Normal no Stuck. 

Stuck loading
![Screenshot_20220917-112054_Chrome.jpg](https://user-images.githubusercontent.com/113487185/190840891-1610bc1e-c599-4c31-863f-c3a88d2bd282.jpg)

Worked
![Screenshot_20220917-112035_Chrome.jpg](https://user-images.githubusercontent.com/113487185/190840886-0abc06e2-ba82-4ec0-b14b-c762ecd5551d.jpg)

Its occured since I take that "while" and "wifi.status" in "if request.. (mode A-A)".
Is my "while" sketch is wrong ? :D

 if I deleted that "while" and logic "Wifi.status" from if request.... the sketch is Normal again. But, we can't get disconnect function to turn off led. hehe

**Comment by wiwidnadw** [comment]
i already try ur code, and i found issue on ur code before the logic.
After i try to disconnecting my ESP32, my ESP32 was freeze. Thats why the code not working well, so sorry.
why thats happens?
1st causes
The code for reconnecting network of ESP32 not working well, so i try to re-code draft

2nd causes
i see many character of "{" and "}" not good, so its make the code broken

so just try this code on ur ESP32 and also for disconnected mode when mode AA, if still fail lets discuss next time


 #include <WiFi.h>

#define led1    26
#define led2    4
#define led3    27
#define led4    14


const char* ssid     = "xxxx";
const char* password = "xxxx";

unsigned long previousMillis = 0;
unsigned long interval = 5000;

WiFiServer server(80);

void startwifi() {
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  Serial.print("Connecting to WiFi ..");
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print('.');
    delay(1000);
  }
  Serial.println(WiFi.localIP());
  server.begin();
}

void setup() {
  Serial.begin(115200);
  

  //initiate pinmode
  pinMode(led1,OUTPUT);
  pinMode(led3,OUTPUT);
  startwifi();
  Serial.print("RSSI: ");
  Serial.println(WiFi.RSSI());
}

void loop() {
  WiFiClient client = server.available();
  String bufflogic;
   
  unsigned long currentMillis = millis();
  
  delay(500);
  // if WiFi is down, try reconnecting every CHECK_WIFI_TIME seconds
  if ((WiFi.status() != 3) && (currentMillis - previousMillis >=interval)) {
    Serial.print(millis());
    Serial.println("Wifi disconnected.");
    if (bufflogic.indexOf("modeaa") !=1) {
          digitalWrite(led1,HIGH);
          digitalWrite(led3,LOW);
    }
    Serial.println("Reconnecting to WiFi...");
    WiFi.disconnect();
    Serial.println("");
    WiFi.begin(ssid, password);
      while (WiFi.status() != 3) {
      Serial.print('.');
      delay(1000);
  }
  Serial.println(WiFi.localIP());
    previousMillis = currentMillis;
    server.begin();
  }

  
 if (!client) {
    return;
  }
  Serial.println("New Client."); 
  while(!client.available()) {
    delay(1);
    return;
  }

  String request = client.readStringUntil('\r');
  Serial.print(request);
  bufflogic = request;
  client.println(bufflogic);

  if(request.indexOf("modeaa") != -1 ) {
    digitalWrite(led1,HIGH);
    digitalWrite(led3,HIGH);
  } 
  
  if(request.indexOf("modebb") != -1 ) {
    digitalWrite(led1,LOW);
    digitalWrite(led3,LOW);
  }

}


for more information about code of connection status, just see this picture
![status call back wifi esp32](https://user-images.githubusercontent.com/63993989/190862718-5a8da396-b66a-48f7-b4a4-0475dea63ef3.png)
